spring:
  datasource:
    url: jdbc:mysql://124.221.253.244:3306/jike_space?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: wlf
    password: wlf
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
#mybatis:
#  mapper-locations: classpath:mapper/*.xml # 扫描所有mapper文件夹中的文件

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出对应信息，当更新数据库时会显示