spring:
  datasource:
    url: jdbc:mysql://175.24.152.204:3306/techwave_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fbcfbcfbc
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

server:
  port: 3367

    #mybatis-plus:
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # log database update info

mapper-locations: classpath*:mapper/*Mapper.xml